Update deployment.yml
pruebas

diff --git a/.github/workflows/deployment.yml b/.github/workflows/deployment.yml
--- a/.github/workflows/deployment.yml
+++ b/.github/workflows/deployment.yml
@@ -52,8 +52,8 @@ jobs:
           -H "Content-Type: application/json" \
           -d '{"user":"010"}')
 
-        if [ "$response" -ne 200 ]; then
-          echo "Error: La respuesta HTTP no es 200, código de estado: $response"
+        if [ "$response" -ne 200 ] && [ "$response" -ne 401 ]; then
+          echo "Error: La respuesta HTTP no es ni 200 ni 401, código de estado: $response"
           cat response.json
           exit 1
         fi
@@ -64,16 +64,19 @@ jobs:
         user_role=$(jq -r '.userRole' response.json)
         user_type_inst=$(jq -r '.userTypeInst' response.json)
 
-        if [ "$status" != "success" ]; then
-          echo "Error: El status no es 'success'"
+        if [ "$status" != "success" ] && [ "$status" != "error" ]; then
+          echo "Error: El status no es 'success' ni 'error'"
           cat response.json
           exit 1
         fi
 
-        if [ -z "$user_name" ] || [ -z "$user_role" ] || [ -z "$user_type_inst" ]; then
-          echo "Error: Los valores de 'userName', 'userRole' o 'userTypeInst' están vacíos"
-          cat response.json
-          exit 1
+        # Si el status es success, validamos los campos de respuesta
+        if [ "$status" == "success" ]; then
+          if [ -z "$user_name" ] || [ -z "$user_role" ] || [ -z "$user_type_inst" ]; then
+            echo "Error: Los valores de 'userName', 'userRole' o 'userTypeInst' están vacíos"
+            cat response.json
+            exit 1
+          fi
         fi
 
         echo "Prueba de usertype exitosa"
@@ -85,8 +88,8 @@ jobs:
           -H "Content-Type: application/json" \
           -d '{"email":"pruebas@gmail.com"}')
 
-        if [ "$response" -ne 200 ]; then
-          echo "Error: La respuesta HTTP no es 200, código de estado: $response"
+        if [ "$response" -ne 200 ] && [ "$response" -ne 401 ]; then
+          echo "Error: La respuesta HTTP no es ni 200 ni 401, código de estado: $response"
           cat response.json
           exit 1
         fi
@@ -96,16 +99,19 @@ jobs:
         user_mail=$(jq -r '.userMail' response.json)
         user_id=$(jq -r '.userId' response.json)
 
-        if [ "$status" != "success" ]; then
-          echo "Error: El status no es 'success'"
+        if [ "$status" != "success" ] && [ "$status" != "error" ]; then
+          echo "Error: El status no es 'success' ni 'error'"
           cat response.json
           exit 1
         fi
 
-        if [ -z "$user_mail" ] || [ -z "$user_id" ]; then
-          echo "Error: Los valores de 'userMail' o 'userId' están vacíos"
-          cat response.json
-          exit 1
+        # Si el status es success, validamos los campos de respuesta
+        if [ "$status" == "success" ]; then
+          if [ -z "$user_mail" ] || [ -z "$user_id" ]; then
+            echo "Error: Los valores de 'userMail' o 'userId' están vacíos"
+            cat response.json
+            exit 1
+          fi
         fi
 
         echo "Prueba de verifyEmail exitosa"
@@ -117,8 +123,8 @@ jobs:
           -H "Content-Type: application/json" \
           -d '{"clave":"010"}')
 
-        if [ "$response" -ne 200 ]; then
-          echo "Error: La respuesta HTTP no es 200, código de estado: $response"
+        if [ "$response" -ne 200 ] && [ "$response" -ne 401 ]; then
+          echo "Error: La respuesta HTTP no es ni 200 ni 401, código de estado: $response"
           cat response.json
           exit 1
         fi
